model:
  type: medmamba
  k-folds: 5
data:
  dataset: chula
  images_dir: [Path to WBC 5000 images directory]
  labels_path: [Path to labels.csv]
  n_classes: 6
  classes:
  - "BNE"
  - "SNE"
  - "Basophil"
  - "Eosinophil"
  - "Monocyte"
  - "Lymphocyte"
params:
  learning_rate: 0.002
  optim_weight_decay: 2.e-4
  batch_size: 8
  epochs: 1