model:
  type: swin_t
  k-folds: 5
data:
  dataset: chula
  images_dir: [Path to WBC 5000 images directory]
  labels_path: [Path to labels.csv]
  n_classes: 6
  classes:
  - "BNE"
  - "SNE"
  - "Basophil"
  - "Eosinophil"
  - "Monocyte"
  - "Lymphocyte"
params:
  learning_rate: 1.e-4
  optim_weight_decay: 5.e-2
  batch_size: 32
  epochs: 5