model:
  type: swin_t
  k-folds: 5
data:
  dataset: chula
  n_classes: 6
  classes:
  - "BNE"
  - "SNE"
  - "Basophil"
  - "Eosinophil"
  - "Monocyte"
  - "Lymphocyte"
params:
  learning_rate: 0.002
  optim_weight_decay: 2e-4
  batch_size: 32
  epochs: 1