name: chula
images_dir: datasets/chula/data/WBC 5000
train_labels_path: datasets/chula/data/labels_train_augmented.csv
test_labels_path: datasets/chula/data/labels_test.csv
n_classes: 6
classes:
- "BNE"
- "SNE"
- "Basophil"
- "Eosinophil"
- "Monocyte"
- "Lymphocyte"